services:
  customerfavorites_application:
    container_name: customerfavorites_application
    depends_on: [redis, mysql]
    build: .
    environment:
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: abc123
      MYSQL_USER: root
      REDIS_HOST: redis
      TZ: America/Sao_Paulo
    ports:
      - '3000:3000/tcp'
    restart: unless-stopped
  redis:
    image: redis
    ports:
      - '6379:6379/tcp'
    environment:
      TZ: America/Sao_Paulo
    restart: 'unless-stopped'
  mysql:
    platform: linux/x86_64
    image: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306/tcp'
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: customerfavoritesdb
      TZ: America/Sao_Paulo
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080/tcp'
    environment:
      TZ: America/Sao_Paulo
